# Welcome to Jekyll!

# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.

# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: La Sierra con Palestina
tagline: ¡No al genocidio!
email: lasierraconpalestina@proton.me
description: Plataforma de vecinas y vecinos de la Sierra del Guadarrama para apoyar al pueblo palestino.
author: Alex Hernandez-Garcia
url: https://lasierraconpalestina.github.io
logo: assets/images/logo/circle_whitebg.png
favicon: assets/images/logo/favicon.png

# Custom variables
hero_image: /assets/images/banner/maldito_seas_estado_de_israel_gradient_green.png
red_pali: "#ce1127ff"
green_pali: "#007a3dff"

# Reading Files
include:
  - _pages

# Collections
collections:
  news:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
